makanan_1 = 15000
makanan_2 = 16000
makanan_3 = 19000
makanan_4 = 20000
makanan_5 = 21000
makanan_6 = 22000

harga_makanan = [makanan_1,makanan_2,makanan_3,makanan_4,makanan_5,makanan_6]
go_cek = 5000

total_pembayaran = (harga_makanan[0] + harga_makanan[1] + harga_makanan[2] + harga_makanan [3] + harga_makanan[4] + harga_makanan[5]  + go_cek)

mata_uang_europe = (total_pembayaran / 20456)

rata_rata = (total_pembayaran / 7)

nim = 50

bolean = (nim != rata_rata)                                                         
#print
print(total_pembayaran)
print(mata_uang_europe)
print(rata_rata)
print(bolean)
print(harga_makanan[-6:])



